services:
  - type: web
    name: vit-explorer
    runtime: docker
    repo: https://github.com/vitnetwork/vit-explorer
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /ping
    autoDeploy: true
    region: oregon
    plan: free
    envVars:
      - key: PORT
        value: "8000"
